name = input("What is your name: ")
school_name = input("What is your school name: ")
number_out_of_ten = input("Pick a number between 1 and 10: ")
number_out_of_one_thousand = input("Pick a number betweeb 100 and 1000: ")
year = input("What year is it: ")
eye_color = input("What is your eye color: ")
age = input("How old are you: ")
breakfast = input("What did you have for breakfast: ")
school_subject = input("What is your favorite school subject: ")
favorite_color = input("What is your favroite color: ")
if name == "Rick Astley":
    print("Wow, a real jokester, but guess what? I'm never gonna give you up, never going to let you down")
else:
    print("Your name is", name, "and you go to",school_name)
print("You are", age, "years old in", year)
print("Your favorite color is", favorite_color, "but your eye color is", eye_color)
print("Your favorite school subject is", school_subject, "and you had", breakfast, "for breakfast")
print("You chose", number_out_of_ten, "and", number_out_of_one_thousand, "for your random numbers")